# Generated by Django 4.0.1 on 2022-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0002_pedido_qtd_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="quantidade",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
