# Generated by Django 4.0.1 on 2022-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0003_alter_produto_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
